#!/bin/bash

# SLiM - Run Lantana simulation replicates
#
# This script runs the SLiM input files generated by the
# corresponding input-generation script.
#
# Each input file represents one independent simulation replicate.
# The replicate number is passed to SLiM as the random seed so that
# each simulation has a different stochastic trajectory.

# Path to the folder containing SLiM input files
input_folder="~/Slim_simulations_cluster/lantana_simulations/100_replicates/migration_10/"

# Simulation parameters
run_on_cluster=1
Nrep=1
Selfrate=0
Nsplit=10
VcfSampleN=50

scenar=scenario0
pwdOUT=~/Slim_simulations_cluster/lantana_simulations/100_replicates/migration_10


# Run each simulation replicate
for i in {1..100}; do

    input_file="${input_folder}${scenar}/inputFile_0_${i}.txt"

    echo "Running SLiM for ${input_file}"

    ~/software/build/slim \
        -d seed=$i \
        -d Selfrate=$Selfrate \
        -d Nrep=$Nrep \
        -d Nsplit=$Nsplit \
        -d VcfSampleN=$VcfSampleN \
        $input_file

done
